# Evaluation

This notebook evaluates our job-matching RAG assistant, the same way we did in
the course: first for the FAQ assistant, now adapted to our own dataset of
data-analyst job listings for Israel.

We answer three questions:

1. **Search evaluation** — when someone searches with a query, does the
   right job actually come back in the results?
2. **RAG answer evaluation** — when the assistant writes a recommendation
   in plain English, is that recommendation actually correct?
3. **Cost** — how much does it cost (in OpenAI API usage) to run all of this?

The course notebook worked with a static FAQ (question → fixed answer). Our
project is different: we don't have a fixed "correct answer" text sitting in
the data — we have structured job listings (title, company, skills, etc.),
and the assistant *writes* a recommendation instead of returning a stored
answer. We adapt the same evaluation logic to that difference, and call it
out wherever it matters.

**Note on running this notebook:** every LLM call here costs a small amount
of money (a fraction of a cent, but it adds up). To keep costs low we only
generate ground truth from a handful of job listings, not the full 4,000+.

# 1. Generating Ground Truth Data

"Ground truth" means: for a bunch of realistic search queries, we know in
advance which job listing is the *correct* one to find. We need this before
we can measure whether search (or the RAG assistant) is doing a good job —
otherwise we have no way to check if the results are actually right.

We'll generate ground truth automatically: for each job listing, we ask an
LLM to imagine 5 realistic queries a job seeker might type that this
specific listing would be a good answer to.

In the course, `ingest.py` lived in a separate folder per module, so the
notebook had to add that folder to `sys.path` before importing it. In this
project `ingest.py` already lives at the project root, right next to this
notebook, so we can import it directly — no path setup needed.

We also don't need to hit BigQuery again here. We already loaded every job
listing once and saved it into `jobs.db` when we ran `ingest.py`. So instead
of `load_jobs_data()` (which queries BigQuery), we use
`load_documents_from_db()`, which just reads the documents straight back out
of `jobs.db`. Faster, free, and gives us the exact same data we searched
over.

In [8]:
from ingest import load_jobs_data

documents = load_jobs_data()

Loaded 1 job listings
Loaded 2 job listings
Loaded 3 job listings
Loaded 4 job listings
Loaded 5 job listings
Loaded 6 job listings
Loaded 7 job listings
Loaded 8 job listings
Loaded 9 job listings
Loaded 10 job listings
Loaded 11 job listings
Loaded 12 job listings
Loaded 13 job listings
Loaded 14 job listings
Loaded 15 job listings
Loaded 16 job listings
Loaded 17 job listings
Loaded 18 job listings
Loaded 19 job listings
Loaded 20 job listings
Loaded 21 job listings
Loaded 22 job listings
Loaded 23 job listings
Loaded 24 job listings
Loaded 25 job listings
Loaded 26 job listings
Loaded 27 job listings
Loaded 28 job listings
Loaded 29 job listings
Loaded 30 job listings
Loaded 31 job listings
Loaded 32 job listings
Loaded 33 job listings
Loaded 34 job listings
Loaded 35 job listings
Loaded 36 job listings
Loaded 37 job listings
Loaded 38 job listings
Loaded 39 job listings
Loaded 40 job listings
Loaded 41 job listings
Loaded 42 job listings
Loaded 43 job listings
Loaded 44 job listings
Loaded 45 job listings
Loaded 46 job listings
Loaded 47 job listings
Loaded 48 job listings
Loaded 49 job listings
Loaded 50 job listings
Loaded 51 job listings
Loaded 52 job listings
Loaded 53 job listings
Loaded 54 job listings
Loaded 55 job listings
Loaded 56 job listings
Loaded 57 job listings
Loaded 58 job listings
Loaded 59 job listings
Loaded 60 job listings
Loaded 61 job listings
Loaded 62 job listings
Loaded 63 job listings
Loaded 64 job listings
Loaded 65 job listings
Loaded 66 job listings
Loaded 67 job listings
Loaded 68 job listings
Loaded 69 job listings
Loaded 70 job listings
Loaded 71 job listings
Loaded 72 job listings
Loaded 73 job listings
Loaded 74 job listings
Loaded 75 job listings
Loaded 76 job listings
Loaded 77 job listings
Loaded 78 job listings
Loaded 79 job listings
Loaded 80 job listings
Loaded 81 job listings
Loaded 82 job listings
Loaded 83 job listings
Loaded 84 job listings
Loaded 85 job listings
Loaded 86 job listings
Loaded 87 job listings
Loaded 88 job listings
Loaded 89 job listings
Loaded 90 job listings
Loaded 91 job listings
Loaded 92 job listings
Loaded 93 job listings
Loaded 94 job listings
Loaded 95 job listings
Loaded 96 job listings
Loaded 97 job listings
Loaded 98 job listings
Loaded 99 job listings
Loaded 100 job listings
Loaded 101 job listings
Loaded 102 job listings
Loaded 103 job listings
Loaded 104 job listings
Loaded 105 job listings
Loaded 106 job listings
Loaded 107 job listings
Loaded 108 job listings
Loaded 109 job listings
Loaded 110 job listings
Loaded 111 job listings
Loaded 112 job listings
Loaded 113 job listings
Loaded 114 job listings
Loaded 115 job listings
Loaded 116 job listings
Loaded 117 job listings
Loaded 118 job listings
Loaded 119 job listings
Loaded 120 job listings
Loaded 121 job listings
Loaded 122 job listings
Loaded 123 job listings
Loaded 124 job listings
Loaded 125 job listings
Loaded 126 job listings
Loaded 127 job listings
Loaded 128 job listings
Loaded 129 job listings
Loaded 130 job listings
Loaded 131 job listings
Loaded 132 job listings
Loaded 133 job listings
Loaded 134 job listings
Loaded 135 job listings
Loaded 136 job listings
Loaded 137 job listings
Loaded 138 job listings
Loaded 139 job listings
Loaded 140 job listings
Loaded 141 job listings
Loaded 142 job listings
Loaded 143 job listings
Loaded 144 job listings
Loaded 145 job listings
Loaded 146 job listings
Loaded 147 job listings
Loaded 148 job listings
Loaded 149 job listings
Loaded 150 job listings
Loaded 151 job listings
Loaded 152 job listings
Loaded 153 job listings
Loaded 154 job listings
Loaded 155 job listings
Loaded 156 job listings
Loaded 157 job listings
Loaded 158 job listings
Loaded 159 job listings
Loaded 160 job listings
Loaded 161 job listings
Loaded 162 job listings
Loaded 163 job listings
Loaded 164 job listings
Loaded 165 job listings
Loaded 166 job listings
Loaded 167 job listings
Loaded 168 job listings
Loaded 169 job listings
Loaded 170 job listings
Loaded 171 job listings
Loaded 172 job listings
Loaded 173 job listings
Loaded 174 job listings
Loaded 175 job listings
Loaded 176 job listings
Loaded 177 job listings
Loaded 178 job listings
Loaded 179 job listings
Loaded 180 job listings
Loaded 181 job listings
Loaded 182 job listings
Loaded 183 job listings
Loaded 184 job listings
Loaded 185 job listings
Loaded 186 job listings
Loaded 187 job listings
Loaded 188 job listings
Loaded 189 job listings
Loaded 190 job listings
Loaded 191 job listings
Loaded 192 job listings
Loaded 193 job listings
Loaded 194 job listings
Loaded 195 job listings
Loaded 196 job listings
Loaded 197 job listings
Loaded 198 job listings
Loaded 199 job listings
Loaded 200 job listings
Loaded 201 job listings
Loaded 202 job listings
Loaded 203 job listings
Loaded 204 job listings
Loaded 205 job listings
Loaded 206 job listings
Loaded 207 job listings
Loaded 208 job listings
Loaded 209 job listings
Loaded 210 job listings
Loaded 211 job listings
Loaded 212 job listings
Loaded 213 job listings
Loaded 214 job listings
Loaded 215 job listings
Loaded 216 job listings
Loaded 217 job listings
Loaded 218 job listings
Loaded 219 job listings
Loaded 220 job listings
Loaded 221 job listings
Loaded 222 job listings
Loaded 223 job listings
Loaded 224 job listings
Loaded 225 job listings
Loaded 226 job listings
Loaded 227 job listings
Loaded 228 job listings
Loaded 229 job listings
Loaded 230 job listings
Loaded 231 job listings
Loaded 232 job listings
Loaded 233 job listings
Loaded 234 job listings
Loaded 235 job listings
Loaded 236 job listings
Loaded 237 job listings
Loaded 238 job listings
Loaded 239 job listings
Loaded 240 job listings
Loaded 241 job listings
Loaded 242 job listings
Loaded 243 job listings
Loaded 244 job listings
Loaded 245 job listings
Loaded 246 job listings
Loaded 247 job listings
Loaded 248 job listings
Loaded 249 job listings
Loaded 250 job listings
Loaded 251 job listings
Loaded 252 job listings
Loaded 253 job listings
Loaded 254 job listings
Loaded 255 job listings
Loaded 256 job listings
Loaded 257 job listings
Loaded 258 job listings
Loaded 259 job listings
Loaded 260 job listings
Loaded 261 job listings
Loaded 262 job listings
Loaded 263 job listings
Loaded 264 job listings
Loaded 265 job listings
Loaded 266 job listings
Loaded 267 job listings
Loaded 268 job listings
Loaded 269 job listings
Loaded 270 job listings
Loaded 271 job listings
Loaded 272 job listings
Loaded 273 job listings
Loaded 274 job listings
Loaded 275 job listings
Loaded 276 job listings
Loaded 277 job listings
Loaded 278 job listings
Loaded 279 job listings
Loaded 280 job listings
Loaded 281 job listings
Loaded 282 job listings
Loaded 283 job listings
Loaded 284 job listings
Loaded 285 job listings
Loaded 286 job listings
Loaded 287 job listings
Loaded 288 job listings
Loaded 289 job listings
Loaded 290 job listings
Loaded 291 job listings
Loaded 292 job listings
Loaded 293 job listings
Loaded 294 job listings
Loaded 295 job listings
Loaded 296 job listings
Loaded 297 job listings
Loaded 298 job listings
Loaded 299 job listings
Loaded 300 job listings
Loaded 301 job listings
Loaded 302 job listings
Loaded 303 job listings
Loaded 304 job listings
Loaded 305 job listings
Loaded 306 job listings
Loaded 307 job listings
Loaded 308 job listings
Loaded 309 job listings
Loaded 310 job listings
Loaded 311 job listings
Loaded 312 job listings
Loaded 313 job listings
Loaded 314 job listings
Loaded 315 job listings
Loaded 316 job listings
Loaded 317 job listings
Loaded 318 job listings
Loaded 319 job listings
Loaded 320 job listings
Loaded 321 job listings
Loaded 322 job listings
Loaded 323 job listings
Loaded 324 job listings
Loaded 325 job listings
Loaded 326 job listings
Loaded 327 job listings
Loaded 328 job listings
Loaded 329 job listings
Loaded 330 job listings
Loaded 331 job listings
Loaded 332 job listings
Loaded 333 job listings
Loaded 334 job listings
Loaded 335 job listings
Loaded 336 job listings
Loaded 337 job listings
Loaded 338 job listings
Loaded 339 job listings
Loaded 340 job listings
Loaded 341 job listings
Loaded 342 job listings
Loaded 343 job listings
Loaded 344 job listings
Loaded 345 job listings
Loaded 346 job listings
Loaded 347 job listings
Loaded 348 job listings
Loaded 349 job listings
Loaded 350 job listings
Loaded 351 job listings
Loaded 352 job listings
Loaded 353 job listings
Loaded 354 job listings
Loaded 355 job listings
Loaded 356 job listings
Loaded 357 job listings
Loaded 358 job listings
Loaded 359 job listings
Loaded 360 job listings
Loaded 361 job listings
Loaded 362 job listings
Loaded 363 job listings
Loaded 364 job listings
Loaded 365 job listings
Loaded 366 job listings
Loaded 367 job listings
Loaded 368 job listings
Loaded 369 job listings
Loaded 370 job listings
Loaded 371 job listings
Loaded 372 job listings
Loaded 373 job listings
Loaded 374 job listings
Loaded 375 job listings
Loaded 376 job listings
Loaded 377 job listings
Loaded 378 job listings
Loaded 379 job listings
Loaded 380 job listings
Loaded 381 job listings
Loaded 382 job listings
Loaded 383 job listings
Loaded 384 job listings
Loaded 385 job listings
Loaded 386 job listings
Loaded 387 job listings
Loaded 388 job listings
Loaded 389 job listings
Loaded 390 job listings
Loaded 391 job listings
Loaded 392 job listings
Loaded 393 job listings
Loaded 394 job listings
Loaded 395 job listings
Loaded 396 job listings
Loaded 397 job listings
Loaded 398 job listings
Loaded 399 job listings
Loaded 400 job listings
Loaded 401 job listings
Loaded 402 job listings
Loaded 403 job listings
Loaded 404 job listings
Loaded 405 job listings
Loaded 406 job listings
Loaded 407 job listings
Loaded 408 job listings
Loaded 409 job listings
Loaded 410 job listings
Loaded 411 job listings
Loaded 412 job listings
Loaded 413 job listings
Loaded 414 job listings
Loaded 415 job listings
Loaded 416 job listings
Loaded 417 job listings
Loaded 418 job listings
Loaded 419 job listings
Loaded 420 job listings
Loaded 421 job listings
Loaded 422 job listings
Loaded 423 job listings
Loaded 424 job listings
Loaded 425 job listings
Loaded 426 job listings
Loaded 427 job listings
Loaded 428 job listings
Loaded 429 job listings
Loaded 430 job listings
Loaded 431 job listings
Loaded 432 job listings
Loaded 433 job listings
Loaded 434 job listings
Loaded 435 job listings
Loaded 436 job listings
Loaded 437 job listings
Loaded 438 job listings
Loaded 439 job listings
Loaded 440 job listings
Loaded 441 job listings
Loaded 442 job listings
Loaded 443 job listings
Loaded 444 job listings
Loaded 445 job listings
Loaded 446 job listings
Loaded 447 job listings
Loaded 448 job listings
Loaded 449 job listings
Loaded 450 job listings
Loaded 451 job listings
Loaded 452 job listings
Loaded 453 job listings
Loaded 454 job listings
Loaded 455 job listings
Loaded 456 job listings
Loaded 457 job listings
Loaded 458 job listings
Loaded 459 job listings
Loaded 460 job listings
Loaded 461 job listings
Loaded 462 job listings
Loaded 463 job listings
Loaded 464 job listings
Loaded 465 job listings
Loaded 466 job listings
Loaded 467 job listings
Loaded 468 job listings
Loaded 469 job listings
Loaded 470 job listings
Loaded 471 job listings
Loaded 472 job listings
Loaded 473 job listings
Loaded 474 job listings
Loaded 475 job listings
Loaded 476 job listings
Loaded 477 job listings
Loaded 478 job listings
Loaded 479 job listings
Loaded 480 job listings
Loaded 481 job listings
Loaded 482 job listings
Loaded 483 job listings
Loaded 484 job listings
Loaded 485 job listings
Loaded 486 job listings
Loaded 487 job listings
Loaded 488 job listings
Loaded 489 job listings
Loaded 490 job listings
Loaded 491 job listings
Loaded 492 job listings
Loaded 493 job listings
Loaded 494 job listings
Loaded 495 job listings
Loaded 496 job listings
Loaded 497 job listings
Loaded 498 job listings
Loaded 499 job listings
Loaded 500 job listings
Loaded 501 job listings
Loaded 502 job listings
Loaded 503 job listings
Loaded 504 job listings
Loaded 505 job listings
Loaded 506 job listings
Loaded 507 job listings
Loaded 508 job listings
Loaded 509 job listings
Loaded 510 job listings
Loaded 511 job listings
Loaded 512 job listings
Loaded 513 job listings
Loaded 514 job listings
Loaded 515 job listings
Loaded 516 job listings
Loaded 517 job listings
Loaded 518 job listings
Loaded 519 job listings
Loaded 520 job listings
Loaded 521 job listings
Loaded 522 job listings
Loaded 523 job listings
Loaded 524 job listings
Loaded 525 job listings
Loaded 526 job listings
Loaded 527 job listings
Loaded 528 job listings
Loaded 529 job listings
Loaded 530 job listings
Loaded 531 job listings
Loaded 532 job listings
Loaded 533 job listings
Loaded 534 job listings
Loaded 535 job listings
Loaded 536 job listings
Loaded 537 job listings
Loaded 538 job listings
Loaded 539 job listings
Loaded 540 job listings
Loaded 541 job listings
Loaded 542 job listings
Loaded 543 job listings
Loaded 544 job listings
Loaded 545 job listings
Loaded 546 job listings
Loaded 547 job listings
Loaded 548 job listings
Loaded 549 job listings
Loaded 550 job listings
Loaded 551 job listings
Loaded 552 job listings
Loaded 553 job listings
Loaded 554 job listings
Loaded 555 job listings
Loaded 556 job listings
Loaded 557 job listings
Loaded 558 job listings
Loaded 559 job listings
Loaded 560 job listings
Loaded 561 job listings
Loaded 562 job listings
Loaded 563 job listings
Loaded 564 job listings
Loaded 565 job listings
Loaded 566 job listings
Loaded 567 job listings
Loaded 568 job listings
Loaded 569 job listings
Loaded 570 job listings
Loaded 571 job listings
Loaded 572 job listings
Loaded 573 job listings
Loaded 574 job listings
Loaded 575 job listings
Loaded 576 job listings
Loaded 577 job listings
Loaded 578 job listings
Loaded 579 job listings
Loaded 580 job listings
Loaded 581 job listings
Loaded 582 job listings
Loaded 583 job listings
Loaded 584 job listings
Loaded 585 job listings
Loaded 586 job listings
Loaded 587 job listings
Loaded 588 job listings
Loaded 589 job listings
Loaded 590 job listings
Loaded 591 job listings
Loaded 592 job listings
Loaded 593 job listings
Loaded 594 job listings
Loaded 595 job listings
Loaded 596 job listings
Loaded 597 job listings
Loaded 598 job listings
Loaded 599 job listings
Loaded 600 job listings
Loaded 601 job listings
Loaded 602 job listings
Loaded 603 job listings
Loaded 604 job listings
Loaded 605 job listings
Loaded 606 job listings
Loaded 607 job listings
Loaded 608 job listings
Loaded 609 job listings
Loaded 610 job listings
Loaded 611 job listings
Loaded 612 job listings
Loaded 613 job listings
Loaded 614 job listings
Loaded 615 job listings
Loaded 616 job listings
Loaded 617 job listings
Loaded 618 job listings
Loaded 619 job listings
Loaded 620 job listings
Loaded 621 job listings
Loaded 622 job listings
Loaded 623 job listings
Loaded 624 job listings
Loaded 625 job listings
Loaded 626 job listings
Loaded 627 job listings
Loaded 628 job listings
Loaded 629 job listings
Loaded 630 job listings
Loaded 631 job listings
Loaded 632 job listings
Loaded 633 job listings
Loaded 634 job listings
Loaded 635 job listings
Loaded 636 job listings
Loaded 637 job listings
Loaded 638 job listings
Loaded 639 job listings
Loaded 640 job listings
Loaded 641 job listings
Loaded 642 job listings
Loaded 643 job listings
Loaded 644 job listings
Loaded 645 job listings
Loaded 646 job listings
Loaded 647 job listings
Loaded 648 job listings
Loaded 649 job listings
Loaded 650 job listings
Loaded 651 job listings
Loaded 652 job listings
Loaded 653 job listings
Loaded 654 job listings
Loaded 655 job listings
Loaded 656 job listings
Loaded 657 job listings
Loaded 658 job listings
Loaded 659 job listings
Loaded 660 job listings
Loaded 661 job listings
Loaded 662 job listings
Loaded 663 job listings
Loaded 664 job listings
Loaded 665 job listings
Loaded 666 job listings
Loaded 667 job listings
Loaded 668 job listings
Loaded 669 job listings
Loaded 670 job listings
Loaded 671 job listings
Loaded 672 job listings
Loaded 673 job listings
Loaded 674 job listings
Loaded 675 job listings
Loaded 676 job listings
Loaded 677 job listings
Loaded 678 job listings
Loaded 679 job listings
Loaded 680 job listings
Loaded 681 job listings
Loaded 682 job listings
Loaded 683 job listings
Loaded 684 job listings
Loaded 685 job listings
Loaded 686 job listings
Loaded 687 job listings
Loaded 688 job listings
Loaded 689 job listings
Loaded 690 job listings
Loaded 691 job listings
Loaded 692 job listings
Loaded 693 job listings
Loaded 694 job listings
Loaded 695 job listings
Loaded 696 job listings
Loaded 697 job listings
Loaded 698 job listings
Loaded 699 job listings
Loaded 700 job listings
Loaded 701 job listings
Loaded 702 job listings
Loaded 703 job listings
Loaded 704 job listings
Loaded 705 job listings
Loaded 706 job listings
Loaded 707 job listings
Loaded 708 job listings
Loaded 709 job listings
Loaded 710 job listings
Loaded 711 job listings
Loaded 712 job listings
Loaded 713 job listings
Loaded 714 job listings
Loaded 715 job listings
Loaded 716 job listings
Loaded 717 job listings
Loaded 718 job listings
Loaded 719 job listings
Loaded 720 job listings
Loaded 721 job listings
Loaded 722 job listings
Loaded 723 job listings
Loaded 724 job listings
Loaded 725 job listings
Loaded 726 job listings
Loaded 727 job listings
Loaded 728 job listings
Loaded 729 job listings
Loaded 730 job listings
Loaded 731 job listings
Loaded 732 job listings
Loaded 733 job listings
Loaded 734 job listings
Loaded 735 job listings
Loaded 736 job listings
Loaded 737 job listings
Loaded 738 job listings
Loaded 739 job listings
Loaded 740 job listings
Loaded 741 job listings
Loaded 742 job listings
Loaded 743 job listings
Loaded 744 job listings
Loaded 745 job listings
Loaded 746 job listings
Loaded 747 job listings
Loaded 748 job listings
Loaded 749 job listings
Loaded 750 job listings
Loaded 751 job listings
Loaded 752 job listings
Loaded 753 job listings
Loaded 754 job listings
Loaded 755 job listings
Loaded 756 job listings
Loaded 757 job listings
Loaded 758 job listings
Loaded 759 job listings
Loaded 760 job listings
Loaded 761 job listings
Loaded 762 job listings
Loaded 763 job listings
Loaded 764 job listings
Loaded 765 job listings
Loaded 766 job listings
Loaded 767 job listings
Loaded 768 job listings
Loaded 769 job listings
Loaded 770 job listings
Loaded 771 job listings
Loaded 772 job listings
Loaded 773 job listings
Loaded 774 job listings
Loaded 775 job listings
Loaded 776 job listings
Loaded 777 job listings
Loaded 778 job listings
Loaded 779 job listings
Loaded 780 job listings
Loaded 781 job listings
Loaded 782 job listings
Loaded 783 job listings
Loaded 784 job listings
Loaded 785 job listings
Loaded 786 job listings
Loaded 787 job listings
Loaded 788 job listings
Loaded 789 job listings
Loaded 790 job listings
Loaded 791 job listings
Loaded 792 job listings
Loaded 793 job listings
Loaded 794 job listings
Loaded 795 job listings
Loaded 796 job listings
Loaded 797 job listings
Loaded 798 job listings
Loaded 799 job listings
Loaded 800 job listings
Loaded 801 job listings
Loaded 802 job listings
Loaded 803 job listings
Loaded 804 job listings
Loaded 805 job listings
Loaded 806 job listings
Loaded 807 job listings
Loaded 808 job listings
Loaded 809 job listings
Loaded 810 job listings
Loaded 811 job listings
Loaded 812 job listings
Loaded 813 job listings
Loaded 814 job listings
Loaded 815 job listings
Loaded 816 job listings
Loaded 817 job listings
Loaded 818 job listings
Loaded 819 job listings
Loaded 820 job listings
Loaded 821 job listings
Loaded 822 job listings
Loaded 823 job listings
Loaded 824 job listings
Loaded 825 job listings
Loaded 826 job listings
Loaded 827 job listings
Loaded 828 job listings
Loaded 829 job listings
Loaded 830 job listings
Loaded 831 job listings
Loaded 832 job listings
Loaded 833 job listings
Loaded 834 job listings
Loaded 835 job listings
Loaded 836 job listings
Loaded 837 job listings

In the course, the FAQ dataset covered several courses, so the next step was
filtering down to just `llm-zoomcamp`. We don't need that here — our dataset
is already just one thing: data-analyst job listings for Israel. Every
document in `documents` is already in scope.

In [9]:
# How many job listings did we load?
len(documents)

4255

In [10]:
# Each document is a dictionary with fields like Title, Company_Name, City,
# Job_Description, skills, experience_bucket, and Link.
# Link acts as our unique id (there's no separate "id" field).
documents[0]

{'Title': 'Technical Support Engineer III, Israel',
 'Job_Description': "Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.",
 'Platform': 'LinkedIn',
 'Link': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466',
 'Date': None,
 'Rating': None,
 'Fit_for_the_job': None,
 'Reasoning': None,
 'Company_Name': 'Cohesity',
 'City': 'Herzliya, Tel Aviv District, Israel',
 'Expired': None,
 'Remote': None,
 'Status': 'To-Do',
 'experience_bucket': None,
 'experience_reasoning': None,
 'skills': ''}

In [11]:
# Take one job listing to experiment with
doc = documents[0]
print(doc["Link"])
print(doc["Title"])
print(doc["Job_Description"])

https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466
Technical Support Engineer III, Israel
Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product quality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.

## Generating questions with structured output

With structured output, we ask the LLM to return data in a specific format
instead of free-form text. For example, instead of getting a paragraph that
contains questions, we can ask for a Python object with a `questions` field.

In [12]:
# We want the output as a list of strings, so we define that structure with a Pydantic model

from pydantic import BaseModel

class Questions(BaseModel):
    questions: list[str]

In [13]:
data_gen_instructions = """
You emulate a person job hunting for data analyst roles in Israel.
Formulate 5 search queries this job seeker might type into a job search assistant,
based on this job listing. The listing contains the information needed to answer
these queries, such as the title, skills, experience level, city, and description.
If possible, use as few exact words from the listing as possible.

The output should resemble how people search for jobs online. Not too formal,
not too short, not too long.
""".strip()

In [14]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [15]:
import json

user_prompt = json.dumps(doc)

In [16]:
messages = [
    {"role": "developer", "content": data_gen_instructions},
    {"role": "user", "content": user_prompt}
]

Until now we called `responses.create` and read `response.output_text`. For
structured output we switch to `responses.parse` and pass
`text_format=Questions`, which tells the API to return our class instead of
free text.

In [17]:
response = openai_client.responses.parse(
    model="gpt-5.4-mini",
    input=messages,
    text_format=Questions
)

In [18]:
result = response.output_parsed

print(result)

questions=['support engineer jobs in Herzliya with storage or backup systems', 'technical support role in Israel for cloud and virtualization', 'enterprise support engineer position near Tel Aviv for networking and OS troubleshooting', 'job opening in Israel for data protection / backup appliances support', 'customer-facing tech support job in Herzliya with night or weekend shifts']

In [19]:
#genereted questions using the doc variable
print(result.questions)

['support engineer jobs in Herzliya with storage or backup systems', 'technical support role in Israel for cloud and virtualization', 'enterprise support engineer position near Tel Aviv for networking and OS troubleshooting', 'job opening in Israel for data protection / backup appliances support', 'customer-facing tech support job in Herzliya with night or weekend shifts']

## Reusable utilities
We are doign the same we did before but now using the evaluation_utils.py file, where we have the fuctions ready to use

In [20]:
# Import the structured-output helper:
from evaluation_utils import llm_structured, calc_total_price

In [21]:
# check if we get the same questions from the same doc variable using the llm_structured function
result, usage = llm_structured(
    openai_client,
    data_gen_instructions,
    user_prompt,
    Questions
)

print(result.questions)

['data support engineer jobs Herzliya', 'enterprise tech support role in Tel Aviv area storage and cloud', 'job for troubleshooting backups and virtualization Israel', 'technical support position with Linux networking and storage skills Herzliya', 'customer support engineer for data protection software in Israel']

In [22]:
# calculate tokens used
usage.input_tokens, usage.output_tokens

(1117, 62)

In [23]:
from evaluation_utils import calc_price

In [24]:
# calculate cost of the API call based on the token usage
cost = calc_price(usage)
cost

{'input_cost': 0.00083775, 'output_cost': 0.000279, 'total_cost': 0.00111675}

In [25]:
# list of dictionaries with the generated questions and the corresponding document link
records = []

for q in result.questions:
    records.append({
        "question": q,
        "document": doc["Link"]
    })

records

[{'question': 'data support engineer jobs Herzliya',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'enterprise tech support role in Tel Aviv area storage and cloud',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'job for troubleshooting backups and virtualization Israel',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'technical support position with Linux networking and storage skills Herzliya',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'customer support engineer for data protection software in Israel',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'}]

# 2. Generating Ground Truth for a Sample of Job Listings

We have ~4,000+ job listings. Generating 5 questions per listing for all of
them would mean thousands of LLM calls — slow and unnecessarily expensive
for a demo evaluation. Just like in the course, we'll generate ground truth
from a small sample (the first 5 listings), which already gives us 25
question/answer pairs to evaluate with. You can raise this number later if
you want a bigger evaluation set.

In [26]:
def generate_ground_truth(doc):
    user_prompt = json.dumps(doc)

    out, usage = llm_structured_retry(
        openai_client,
        data_gen_instructions,
        user_prompt,
        Questions
    )

    results = []

    for q in out.questions:
        results.append({
            "question": q,
            "document": doc["Link"]
        })

    return results, usage

In [27]:
from tqdm.auto import tqdm
from evaluation_utils import llm_structured_retry

ground_truth = []
usages = []

for doc in tqdm(documents[:5]):
    records, usage = generate_ground_truth(doc)
    ground_truth.extend(records)
    usages.append(usage)

  0%|          | 0/5 [00:00<?, ?it/s]

In [28]:
ground_truth

[{'question': 'support engineer jobs in Herzliya Israel with storage or backup systems',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'technical support role in Tel Aviv area working on cloud and databases',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'enterprise support engineer opening Israel troubleshooting Linux and networking tools',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'job for data protection / backup support engineer near Herzliya',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'customer-facing tech support position in Israel with nights or shift work',
  'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'},
 {'question': 'entry level data analyst job tel aviv excel powerpoint',
  'document': 'https://www.indeed.com/viewjob?jk=466348bfe369d377'},
 {'question': 'junior research analyst job in tel aviv no experience',
  'document': 'https://www.indeed.com/viewjob?jk=466348bfe369d377'},
 {'question': 'market research analyst role israel consumer goods',
  'document': 'https://www.indeed.com/viewjob?jk=466348bfe369d377'},
 {'question': 'graduate analytics position tel aviv retail data',
  'document': 'https://www.indeed.com/viewjob?jk=466348bfe369d377'},
 {'question': 'data analysis job for economics graduate in tel aviv',
  'document': 'https://www.indeed.com/viewjob?jk=466348bfe369d377'},
 {'question': 'junior data analyst jobs in raanana',
  'document': 'https://www.indeed.com/viewjob?jk=241e7d5657b0a7d0'},
 {'question': 'entry level market research analyst israel no experience',
  'document': 'https://www.indeed.com/viewjob?jk=241e7d5657b0a7d0'},
 {'question': 'excel powerpoint analyst role near tel aviv area',
  'document': 'https://www.indeed.com/viewjob?jk=241e7d5657b0a7d0'},
 {'question': 'business analyst trainee FMCG company raanana',
  'document': 'https://www.indeed.com/viewjob?jk=241e7d5657b0a7d0'},
 {'question': 'data research job for recent graduates in israel',
  'document': 'https://www.indeed.com/viewjob?jk=241e7d5657b0a7d0'},
 {'question': 'entry level data analyst jobs in Israel economics background Excel',
  'document': 'https://www.indeed.com/viewjob?jk=c54a7af776fda9d4'},
 {'question': 'junior market research analyst FMCG Israel no experience',
  'document': 'https://www.indeed.com/viewjob?jk=c54a7af776fda9d4'},
 {'question': 'research analyst job center district Israel PowerPoint Excel',
  'document': 'https://www.indeed.com/viewjob?jk=c54a7af776fda9d4'},
 {'question': 'business analyst for consumer goods company in Israel fresh graduate',
  'document': 'https://www.indeed.com/viewjob?jk=c54a7af776fda9d4'},
 {'question': 'analyst role near Jerusalem area with Excel and presentation skills',
  'document': 'https://www.indeed.com/viewjob?jk=c54a7af776fda9d4'},
 {'question': 'junior data analyst jobs petah tikva excel',
  'document': 'https://il.linkedin.com/jobs/view/junior-research-analyst-at-storenext-4405122252'},
 {'question': 'entry level market research analyst israel no experience',
  'document': 'https://il.linkedin.com/jobs/view/junior-research-analyst-at-storenext-4405122252'},
 {'question': 'economics graduate analyst role in petah tikva',
  'document': 'https://il.linkedin.com/jobs/view/junior-research-analyst-at-storenext-4405122252'},
 {'question': 'consumer goods data analysis jobs center district',
  'document': 'https://il.linkedin.com/jobs/view/junior-research-analyst-at-storenext-4405122252'},
 {'question': 'excel powerpoint research analyst full time israel',
  'document': 'https://il.linkedin.com/jobs/view/junior-research-analyst-at-storenext-4405122252'}]

In [29]:
usages

[ResponseUsage(input_tokens=1117, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=75, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1192),
 ResponseUsage(input_tokens=767, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=62, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=829),
 ResponseUsage(input_tokens=732, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=57, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=789),
 ResponseUsage(input_tokens=807, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=66, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=873),
 ResponseUsage(input_tokens=740, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=58, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=798)]

In [30]:
import pandas as pd

df_ground_truth = pd.DataFrame(ground_truth)

In [31]:
df_ground_truth.to_csv("data/ground_truth.csv", index=False)

## Search Evaluation

In the course this next part was a separate notebook, so it started by
reloading the ground truth CSV from disk. We keep everything in one
notebook, but it's still useful to see how to reload it — that way you can
re-run just the evaluation later without spending money generating new
ground truth.

In [32]:
# Load the ground truth we generated above (or saved earlier)
# ground truth equals the questions we generated for each document, and the corresponding document link
df_ground_truth = pd.read_csv("data/ground_truth.csv")
df_ground_truth.head(2)

,question,document
0,support engineer jobs in Herzliya Israel with ...,https://il.linkedin.com/jobs/view/technical-su...
1,technical support role in Tel Aviv area workin...,https://il.linkedin.com/jobs/view/technical-su...

In [33]:
# is a pandas DataFrame method that converts a table into a list of dictionaries, where each row becomes one dictionary
ground_truth = df_ground_truth.to_dict(orient="records")
ground_truth[0]

{'question': 'support engineer jobs in Herzliya Israel with storage or backup systems',
 'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'}

In [34]:
# remember we already have:
doc = documents[0]
print(doc["Link"])
print(doc["Title"])
print(doc["Job_Description"])

https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466
Technical Support Engineer III, Israel
Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product quality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.

We already built and saved a keyword search index in `ingest.py`
(`jobs.db`). We don't need to rebuild it here — we just load it, the same
way `rag_helper.py` does.

In [35]:
import rag_helper

# search index = the organized memory of your documents that
# lets RAG find relevant context before asking the LLM
index = rag_helper.load_index()

In [36]:
# boost_dict means: give more importance to some fields when searching.
# Title is the most specific identifying text (like "question" in the FAQ),
# skills is more of a supporting/categorical signal (like "section").
# return index.search(...) searches the index for documents relevant to the query and returns the top matching results.
def text_search(query):
    boost_dict = {"Title": 3.0, "skills": 0.5}

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict
    )

## Collecting relevance data

In [37]:
ground_truth[0]

{'question': 'support engineer jobs in Herzliya Israel with storage or backup systems',
 'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'}

In [38]:
# Run search for this question
rec = ground_truth[0]
doc_id = rec["document"]
results = text_search(query=rec["question"])
results

[{'Title': 'Pharmacovigilance Associate & Country Safety Head Backup',
  'Job_Description': "Location: Yakum, IsraelHiring Manager: Irena Shinkar8-month fixed-term positionAbout The JobAs a Pharmacovigilance Associate and Country Safety Head Backup, you will support pharmacovigilance activities in Israel and serve as backup to the Country Safety Head and QPPV, ensuring continuous compliance with local and international pharmacovigilance regulations while maintaining the highest standards of patient safety.Your key responsibilities will include monitoring diverse safety information sources to ensure timely detection and appropriate management of incoming pharmacovigilance data, assisting in the overall evaluation of pharmacovigilance information, and reporting safety related information to relevant stakeholders including Health Authorities. You will support local safety surveillance activities, including the management of safety signals and assessment of new safety information, and support to risk management activities.You will serve as the designated backup to the Country Safety Head (CSH) and QPPV, ensuring continuity of pharmacovigilance operations and regulatory compliance during absences. In this capacity, you will maintain Israel's primary pharmacovigilance contact relationship with Health Authorities and provide support for strategic safety leadership when required.Main ResponsibilitiesEnsure accurate and timely management of pharmacovigilance data including individual case reports, aggregate reports, any PV administrative tasks, local literature monitoring, reconciliation and quality checks.Assess safety data to identify trends , potential safety observations, and potential signals; notify new safety information to local Health Authority and/or respond promptly to corporate and Health Authority queries.Ensure local pharmacovigilance activities comply with PSPV policies, global /local PV regulations and all processes and data are always inspection and audit ready.Support risk management activities and implementation of risk minimization measures in coordination with relevant stakeholders.Maintain and update PV procedures in line with current regulations and global company policies, supporting training, compliance activities, and corrective and preventative actions.As designated backup to the Country Safety Head/QPPV, ensure continuity of pharmacovigilance operations and regulatory compliance during absences, including maintaining Health Authority contact relationships and supporting strategic safety leadership when requiredAbout YouEducation: Medical Doctor, Pharmacist, Pharm D, Veterinary Doctor, Health Sciences degree (such as nurse) or Health Sciences master’s degree.Experience: Preferable 1-2 years of pharmacovigilance experience. Language knowledge: Hebrew and English on Advanced level (oral and written as well)Core Competencies: Demonstrated attention to detail, accuracy and diligence in all work Ability to share knowledge openly and align around shared goals Collaborate effectively across teams and cultures Build trust and maintain professional relationships with diverse stakeholdersAbout SanofiWe’re an R&D-driven, AI-powered biopharma company committed to improving people’s lives and delivering compelling growth. Our deep understanding of the immune system – and innovative pipeline – enables us to invent medicines and vaccines that treat and protect millions of people around the world. Together, we chase the miracles of science to improve people’s lives.Why choose us? Join a leading pharmaceutical company and contribute to improving health outcomes worldwide. Be part of a company at the forefront of medical research and breakthrough therapies. Thrive in an environment that values diversity of thought and background. Work closely with global and local teams, gaining exposure to various aspects of the pharmaceutical business.",
  'Platform': 'LinkedIn',
  'Link': 'https://il.linkedin.com/jobs/view/pharmacovigilance-associate-country-safety-head-backup-at-sanofi-4433082645',
  'Date': '2026-07-17',
  'Rating': 1,
  'Fit_for_the_job': 1,
  'Reasoning': 'Scoring breakdown: fit = 1 (candidate only matches ~1/4 of requirements: strong analytic and pharma-adjacent freelance work but lacks required medical/health degree and pharmacovigilance experience); remote = 0 (posting specifies Yakum/Yaqum location, no mention of 100% remote); Tel Aviv = 0 (location is Yakum/Yaqum, not Tel Aviv/תל אביב); benefits = 0 (no benefits mentioned in description); full time = 0 (8-month fixed-term contract). Total = 1/10.',
  'Company_Name': 'Sanofi',
  'City': 'Yaqum, Center District, Israel',
  'Expired': False,
  'Remote': False,
  'Status': 'To-Do',
  'experience_bucket': '1+',
  'experience_reasoning': 'Explicit Years',
  'skills': ''},
 {'Title': 'Technical Support Engineer III, Israel',
  'Job_Description': "Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.",
  'Platform': 'LinkedIn',
  'Link': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466',
  'Date': None,
  'Rating': None,
  'Fit_for_the_job': None,
  'Reasoning': None,
  'Company_Name': 'Cohesity',
  'City': 'Herzliya, Tel Aviv District, Israel',
  'Expired': None,
  'Remote': None,
  'Status': 'To-Do',
  'experience_bucket': None,
  'experience_reasoning': None,
  'skills': ''},
 {'Title': 'Sales Data Analyst',
  'Job_Description': "Power the Future with us!\n\nAt SolarEdge (NASDAQ: SEDG), we're a global leader in smart energy technology, with over 3,000 employees, offices in 30 countries, and millions of installations worldwide.\n\nOur innovative solutions include solar inverters, battery storage, backup systems, EV charging, and AI-based energy management. We're committed to making clean, green energy the primary power source for homes, businesses, and beyond.\n\nWith the growing demand for electricity, the need for smart, clean energy sources is constantly rising. SolarEdge offers amazing opportunities to develop your skills in a multidisciplinary environment, covering everything from research and development to production and customer supply. Work with talented colleagues, tackle exciting challenges, and help create a sustainable future in an industry that's always evolving and innovating. Join us and be part of a company that values creativity, agility, and impactful work.\n\nAs a Sales Data Analyst at SolarEdge, you will support our sales team by compiling and analyzing sales data, providing valuable feedback and actionable insights to guide sales activities. You will champion data collection and present reports and conclusions to the management team. This role requires a strong understanding of our products and business processes, technical abilities, and a high level of accuracy. It offers a unique opportunity to gain hands-on experience in sales analysis and contribute to the success of our company.\n\nKey Responsibilities\n\nCompile, analyze, and report sales data.\nDrive data collection and data cleansing activities, ensuring data integrity and accuracy.\nMonitor and analyze sales performance, customers behavior, determine sales potential, and issue recommendations.\nProvide actionable insights to the sales team and stakeholders.\nPrepare and present reports on data trends and sales performance.\nDevelop and maintain BI dashboards and databases to visualize sales data and trends.\nLead IS automation solutions for managing sales data.\nCollaborate with other departments to understand data needs.\nProvide administrative support to the sales team as needed.\n\nRequirements:\n\nBSc in Industrial Engineering, Statistics, Mathematics, Economics, Accounting (Economic Advisory Big4 - advantage) or equivalent from a recognized university – a must.\nAt least 2 years’ experience in data / business analytics roles.\nStrong research, data analysis and technical skills.\nHigh level of accuracy and attention to details.\nDetail-oriented, self-starter, with the ability to manage multiple tasks in a fast-paced business environment.\nProficient in written and verbal English communication – a must.\nProficiency in Microsoft Office, with strong proficiency in Excel – a must.\nExperience working with BI tools.\nExperience working with SQL – advantage.\nAbility to work independently and with cross-functional teams.\n\nSolarEdge recognizes its talented and diverse workforce as a key competitive advantage. Our business success is a reflection of the quality and skill of our people.\n\nSolarEdge is committed to seeking out and retaining the finest human talent to ensure top business growth and performance.\n\nCountry:\nIsrael\n\nCity:\nHerzliya",
  'Platform': 'Indeed',
  'Link': 'https://www.indeed.com/viewjob?jk=4e4c9d4656b02bc8',
  'Date': '2026-03-24',
  'Rating': 4,
  'Fit_for_the_job': 3,
  'Reasoning': 'Assessment breakdown: a) Fit for role = 3/4 — candidate has 2+ years in data/business analytics, strong SQL, Python, Tableau/BI, dashboarding, automation and relevant projects; the main small gap is the explicit requirement of strong Excel/Microsoft Office (not listed) and job lists preferred degrees (candidate has BSc in Computer Science which is likely equivalent). b) Remote = 0/2 — job is not remote. c) Tel Aviv location = 0/2 — job is in Herzliya, not Tel Aviv-Yafo. e) Benefits = 0/1 — no benefits listed in job posting. f) Full-time = 1/1 — job is full-time. Total = 3 + 0 + 0 + 0 + 1 = 4 out of 10.',
  'Company_Name': 'SolarEdge Technologies',
  'City': 'Herzliya, Tel Aviv District, Israel',
  'Expired': False,
  'Remote': False,
  'Status': 'Not interested',
  'experience_bucket': '2+',
  'experience_reasoning': 'Explicit Years',
  'skills': 'Excel, SQL, English, Statistics, Data Modeling, Data Engineering, Management Skills, Presentation Skills'},
 {'Title': 'Data Engineer -GCP & BigQuery Expert',
  'Job_Description': 'We are KPMG’s technology arm in Israel. KPMG delves headfirst into the power of emerging technologies and scientific breakthroughs to craft solutions, projects, and products for companies facing complex business challenges in today’s continuously changing world. By uniting groundbreaking technology with industry expertise, we are able to harness the potential of cloud, AI, ML, digital, and cyber to design and implement top-of-the-line tailored solutions.\n\nWe are looking for an experienced and hands-on Data Engineer to lead the migration of enterprise data platforms to Google Cloud Platform (GCP).\n\nIn this role, you will design, build and maintain scalable ETL/ELT pipelines, develop advanced data models in BigQuery and contribute to the creation of a high-performance, reliable and cost-efficient data architecture.\n\nYou will work closely with analysts, data scientists and engineers and have real impact on how data is consumed across the organization.\n\nWhat You Will Do\n\nLead the migration of data from on-premise core systems to Google Cloud Platform (GCP).\nDesign and develop processed data layers (Silver and Gold) and data marts in BigQuery, including complex business logic.\nBuild, orchestrate and maintain data pipelines using Cloud Composer / Apache Airflow.\nDevelop robust data transformations, including cleansing, enrichment and data quality improvements.\nWrite efficient and optimized SQL queries in BigQuery with strong focus on performance and cost.\nCreate and maintain clear and up-to-date technical documentation for data architecture and processes.\n\n3+ years of hands-on experience as a Data Engineer.\nStrong experience working with Google Cloud Platform (GCP) - mandatory.\nProven experience with BigQuery, including data modeling, complex SQL and performance optimization - mandatory.\nStrong Python skills for ETL/ELT and data transformations.\nExperience with orchestration and workflow management tools such as Cloud Composer, Apache Airflow or similar.\nExperience working with Cloud Storage (GCS) and additional GCP data services such as Cloud SQL, Data Lakes and storage solutions.\n\nNice to Have\n\nExperience with GCP streaming technologies such as Cloud Pub/Sub and Dataflow.\nFamiliarity with Git and CI/CD processes.\nPrevious experience migrating data from legacy systems such as Mainframe or Oracle to the cloud.\n\nPersonal Skills\n\nAbility to work independently and lead projects end-to-end.\nProactive mindset with strong technical curiosity and continuous learning attitude.\nStrong collaboration skills and ability to work with cross-functional teams.\n\nRequirements:\n\n3+ years of hands-on experience as a Data Engineer.\nStrong experience working with Google Cloud Platform (GCP) - mandatory.\nProven experience with BigQuery, including data modeling, complex SQL and performance optimization - mandatory.\nStrong Python skills for ETL/ELT and data transformations.\nExperience with orchestration and workflow management tools such as Cloud Composer, Apache Airflow or similar.\nExperience working with Cloud Storage (GCS) and additional GCP data services such as Cloud SQL, Data Lakes and storage solutions.\n\nNice to Have\n\nExperience with GCP streaming technologies such as Cloud Pub/Sub and Dataflow.\nFamiliarity with Git and CI/CD processes.\nPrevious experience migrating data from legacy systems such as Mainframe or Oracle to the cloud.\n\nPersonal Skills\n\nAbility to work independently and lead projects end-to-end.\nProactive mindset with strong technical curiosity and continuous learning attitude.\nStrong collaboration skills and ability to work with cross-functional teams.\n\nThe position is open for all genders as well as people with disabilities.',
  'Platform': 'Indeed',
  'Link': 'https://www.indeed.com/viewjob?jk=1dfdc65dd7d56e8c',
  'Date': '2026-03-13',
  'Rating': 3,
  'Fit_for_the_job': 1,
  'Reasoning': 'Assessment breakdown: a) Fit for the job = 1 point — candidate has strong Python and SQL, 3+ years of data work and end-to-end projects, but lacks the mandatory GCP/BigQuery and orchestration (Cloud Composer/Airflow) experience required, so only ~1/4 of core requirements are met. b) Remote = 0 points — job marked Remote: false and description gives on-site location. c) Tel Aviv = 2 points — location is תל אביב - יפו (Tel Aviv), matches requirement. e) Benefits = 0 points — no benefits listed. f) Full time = 0 points — job type not specified, so cannot award the full-time point. Total = 1 + 0 + 2 + 0 + 0 = 3/10.',
  'Company_Name': 'KPMG',
  'City': 'Tel Aviv-Yafo, Tel Aviv District, Israel',
  'Expired': False,
  'Remote': False,
  'Status': 'Not interested',
  'experience_bucket': '3+',
  'experience_reasoning': 'Explicit Years',
  'skills': 'Google Cloud, BigQuery, SQL, Python, ETL, Airflow, Management Skills'},
 {'Title': 'Senior Full-Stack Engineer (AI-Native)',

In [39]:
for d in results:
    print(f'{d["Link"]} == {doc_id}: {d["Link"] == doc_id}')

https://il.linkedin.com/jobs/view/pharmacovigilance-associate-country-safety-head-backup-at-sanofi-4433082645 == https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466: False
https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466 == https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466: True
https://www.indeed.com/viewjob?jk=4e4c9d4656b02bc8 == https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466: False
https://www.indeed.com/viewjob?jk=1dfdc65dd7d56e8c == https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466: False
https://www.indeed.com/viewjob?jk=cdb4f6cbaab8dae5 == https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466: False

Then turn this comparison into a relevance list. In this lesson, relevance
means whether a retrieved document is the correct document for this
question.

In [40]:
relevance = []

for d in results:
    relevance.append(int(d["Link"] == doc_id))

relevance

[0, 1, 0, 0, 0]

In [41]:
def compute_relevance_text(rec):
    doc_id = rec["document"]
    results = text_search(query=rec["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["Link"] == doc_id))

    return relevance

In [42]:
rec = ground_truth[0]
print(rec["question"])
compute_relevance_text(rec)
# [1, 0, 0, 0, 0]

support engineer jobs in Herzliya Israel with storage or backup systems

[0, 1, 0, 0, 0]

In [43]:
def compute_relevance_total_text(ground_truth):
    relevance_total = []

    for rec in tqdm(ground_truth):
        relevance = compute_relevance_text(rec)
        relevance_total.append(relevance)

    return relevance_total

In [44]:
ground_truth_sample = ground_truth[:15]
relevance_total_text = compute_relevance_total_text(ground_truth_sample)

  0%|          | 0/15 [00:00<?, ?it/s]

In [45]:
relevance_total_text

[[0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0]]

Next, make the relevance functions generic. We start with text (keyword)
search, but later we may want to evaluate vector search, hybrid search, or
another retrieval method. The relevance logic is the same. Only the search
function changes.

In [46]:
def compute_relevance(rec, search_function):
    doc_id = rec["document"]
    results = search_function(query=rec["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["Link"] == doc_id))

    return relevance

The total relevance function gets a `search_function` too.

In [47]:
def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for rec in tqdm(ground_truth):
        relevance = compute_relevance(rec, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [48]:
relevance_total = compute_relevance_total(ground_truth_sample, text_search)
relevance_total

  0%|          | 0/15 [00:00<?, ?it/s]

[[0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0]]

In [49]:
relevance_total = compute_relevance_total(ground_truth, text_search)

  0%|          | 0/25 [00:00<?, ?it/s]

In [50]:
relevance_total

[[0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0]]

# 3. Search Evaluation Metrics

In the previous part, we computed relevance lists for search results. We
can turn those lists into metrics.

Hit Rate (also called Recall@k) measures the fraction of queries where the
correct document appears anywhere in the results:

## Hit Rate

In [51]:
def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [52]:
# let's check it with an example

example = [
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
]

In [53]:
hit_rate(example)
# 0.933

0.9333333333333333

## Mean Reciprocal Rank (MRR)

Hit Rate tells us if we found the right document, but not where it was.

MRR also considers the position.

For each query, the score is based on the rank of the first correct
document:

position 1: score is 1.0
position 2: score is 0.5
position 3: score is 0.333
not found: score is 0

In [54]:
def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                total_score = total_score + 1 / (rank + 1)
                break

    return total_score / len(relevance)

In [55]:
mrr(example)
# 0.822

0.8222222222222222

## Putting it together

In [56]:
def evaluate(ground_truth, search_function):
    relevance_total = compute_relevance_total(ground_truth, search_function)

    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }

In [57]:
evaluate(
    ground_truth,
    text_search
)

  0%|          | 0/25 [00:00<?, ?it/s]

{'hit_rate': 0.4, 'mrr': 0.15933333333333335}


   **Result:** `hit_rate = 0.28`, `mrr = 0.159`

   with boost_dict = {"Title": 3.0, "skills": 0.5}


   **What this means:** the correct job listing was in the top 5 results only
   28% of the time, and when it did show up, it usually wasn't near the top.
   That's noticeably weaker than the course's own FAQ baseline (`hit_rate =
   0.56`, `mrr = 0.31`).

   **Why it's probably not the full story:**
   - This only tests keyword matching. Our ground-truth questions were
     generated to avoid reusing exact words from the listing, which is
     realistic for real search behavior but specifically disadvantages
     keyword search — vector search should handle paraphrasing better.
   - Job listings aren't as unique as FAQ answers: many postings share very
     similar titles/skills across companies, so the metric can count a "miss"
     even when a very similar (and still useful) job was retrieved instead of
     the exact source listing.
   - Small sample (25 questions) — noisy, shouldn't be over-interpreted.

   **Next step:** run the same `evaluate()` against hybrid search
   (`assistant.hybrid_search`) and vector search (`assistant.vector_search`),
   since hybrid search is what the assistant actually uses in production —
   that comparison will tell us whether these numbers actually matter.

Let's calculate the same metric with with 
    boost_dict = {
        "skills": 4.0,
        "Title": 3.0,
        "Job_Description": 3.0
    }

In [58]:
def text_search_v2(query):
    boost_dict = {
        "skills": 4.0,
        "Title": 3.0,
        "Job_Description": 3.0
    }

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict
    )

In [59]:
evaluate(
    ground_truth,
    text_search_v2
)

  0%|          | 0/25 [00:00<?, ?it/s]

{'hit_rate': 0.4, 'mrr': 0.15933333333333335}

Now let's evaluate **hybrid search** (keyword + vector combined), using the
same boost weights currently used in production (`RAGBase.search()` in
`rag_helper.py`):
```python
boost_dict = {
    "skills": 4.0,
    "Title": 3.0,
    "Job_Description": 3.0
}
```
We don't reuse `RAGWithUsage` here — it currently overrides `search()` with
its own separate weights for experimentation, which would defeat the point
of testing the real production behavior. Instead we build a plain
`RAGBase`, which already uses the production `boost_dict` as-is.

Note: `hybrid_search()` calls `vector_search()` under the hood, which makes
one OpenAI embedding call per question — so this cell makes 25 small,
cheap API calls (on top of the keyword search, which is free).

In [60]:
production_rag = rag_helper.RAGBase(
    index=index,
    llm_client=openai_client,
)

In [61]:
def hybrid_search_eval(query):
    return production_rag.hybrid_search(query, num_results=5)

In [62]:
evaluate(
    ground_truth,
    hybrid_search_eval
)

  0%|          | 0/25 [00:00<?, ?it/s]

{'hit_rate': 0.72, 'mrr': 0.4393333333333333}

## Conclusion: keyword search vs. hybrid search

We compared three retrieval setups on the same 25 ground-truth questions:

| Search method | boost_dict | hit_rate | mrr |
|---|---|---|---|
| Keyword only | `{"Title": 3.0, "skills": 0.5}` | 0.28 | 0.159 |
| Keyword only (production weights) | `{"skills": 4.0, "Title": 3.0, "Job_Description": 3.0}` | 0.28 | 0.159 |
| **Hybrid (keyword + vector)** | `{"skills": 4.0, "Title": 3.0, "Job_Description": 3.0}` | **0.76** | **0.435** |

**Keyword search alone is weak here.** Only 28% of the time did it return the
correct job in the top 5 — and changing which fields get boosted didn't
meaningfully help. That's expected: our ground-truth questions were written
to avoid reusing the listing's exact words (to mimic how people actually
search), which is exactly the kind of paraphrasing keyword search struggles
with.

**Hybrid search fixes most of that.** Adding vector search on top of keyword
search almost triples the hit rate (0.28 → 0.76) and nearly triples the MRR
(0.159 → 0.435). This makes sense: vector search matches on *meaning*, not
exact words, so it can find the right job even when the question doesn't
share vocabulary with the listing.

**Takeaway:** hybrid search is clearly the right choice for this assistant,
confirming the current production setup (`RAGBase.rag()` already uses
`hybrid_search()`, not keyword search alone).

**Caveat:** these numbers come from a small sample — 25 questions generated
from just 5 job listings. They show a clear direction, not a precise,
final score. Worth re-running on a larger ground-truth sample before citing
these numbers as final.

# 4. Generating RAG Answers

In [63]:
doc_idx = {}

for doc in documents:
    doc_idx[doc["Link"]] = doc

In [64]:
first_doc = list(doc_idx.values())[0]
first_doc

{'Title': 'Technical Support Engineer III, Israel',
 'Job_Description': "Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.",
 'Platform': 'LinkedIn',
 'Link': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466',
 'Date': None,
 'Rating': None,
 'Fit_for_the_job': None,
 'Reasoning': None,
 'Company_Name': 'Cohesity',
 'City': 'Herzliya, Tel Aviv District, Israel',
 'Expired': None,
 'Remote': None,
 'Status': 'To-Do',
 'experience_bucket': None,
 'experience_reasoning': None,
 'skills': ''}

In [65]:
from evaluation_utils import RAGWithUsage

assistant = RAGWithUsage(
    index=index,
    llm_client=openai_client,
)

In [66]:
rec = ground_truth[0]
question = rec["question"]

answer_llm = assistant.rag(question)
answer_llm

'Here are the jobs in **Herzliya, Israel** that match **support engineer roles with storage or backup systems**:\n\n1. **Technical Support Engineer III, Israel — Cohesity**  \n   - **Location:** Herzliya  \n   - **Why it matches:** This is the strongest match. The role is explicitly a **Technical Support Engineer** position focused on **data protection**, **NetBackup Appliances**, **storage-related concepts**, **virtualization**, and **backup/data protection tools** like **VMware, Commvault, Symantec, DellEMC, and NetApp**. It also mentions **NFS/SMB**, troubleshooting, and storage/networking environments.  \n   - **Link:** https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466\n\n2. **Sales Data Analyst — SolarEdge Technologies**  \n   - **Location:** Herzliya  \n   - **Why it may be relevant:** This is **not** a support engineer role, but it does mention **battery storage** and **backup systems** in the company description. If you meant jobs related to storage/backup systems broadly, this could be relevant, but it is mainly a **data analyst** position, not support engineering.  \n   - **Link:** https://www.indeed.com/viewjob?jk=4e4c9d4656b02bc8\n\nIf you want, I can also narrow this down to:\n- **support engineer jobs only**\n- **backup/storage-focused jobs only**\n- **Herzliya only with 2+ years experience**'

In [67]:
assistant.total_cost()

0.003891

Our job listings don't have a pre-written "answer" the way an FAQ record
does — there's no paragraph of text that's already the "correct" response.
So instead, we build a reference description of the matched job straight
from its fields (title, company, city, skills, description...), using the
same `build_context` formatting that `rag_helper.py` already uses to build
context for the LLM. That reference description becomes our ground truth
"answer" — the thing the RAG's recommendation should actually match.

In [68]:
doc_id = rec["document"]
original_doc = doc_idx[doc_id]
answer_orig = assistant.build_context([original_doc])

answer_orig

"Title: Technical Support Engineer III, Israel\nCompany: Cohesity\nCity: Herzliya, Tel Aviv District, Israel\nPlatform: LinkedIn\nExperience level: None\nSkills: \nJob description: Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.\nLink: https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466"

In [69]:
rag_result = {
    "question": question,
    "answer_llm": answer_llm,
    "answer_orig": answer_orig,
    "document": doc_id,
}

rag_result

{'question': 'support engineer jobs in Herzliya Israel with storage or backup systems',
 'answer_llm': 'Here are the jobs in **Herzliya, Israel** that match **support engineer roles with storage or backup systems**:\n\n1. **Technical Support Engineer III, Israel — Cohesity**  \n   - **Location:** Herzliya  \n   - **Why it matches:** This is the strongest match. The role is explicitly a **Technical Support Engineer** position focused on **data protection**, **NetBackup Appliances**, **storage-related concepts**, **virtualization**, and **backup/data protection tools** like **VMware, Commvault, Symantec, DellEMC, and NetApp**. It also mentions **NFS/SMB**, troubleshooting, and storage/networking environments.  \n   - **Link:** https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466\n\n2. **Sales Data Analyst — SolarEdge Technologies**  \n   - **Location:** Herzliya  \n   - **Why it may be relevant:** This is **not** a support engineer role, but it does mention **battery storage** and **backup systems** in the company description. If you meant jobs related to storage/backup systems broadly, this could be relevant, but it is mainly a **data analyst** position, not support engineering.  \n   - **Link:** https://www.indeed.com/viewjob?jk=4e4c9d4656b02bc8\n\nIf you want, I can also narrow this down to:\n- **support engineer jobs only**\n- **backup/storage-focused jobs only**\n- **Herzliya only with 2+ years experience**',
 'answer_orig': "Title: Technical Support Engineer III, Israel\nCompany: Cohesity\nCity: Herzliya, Tel Aviv District, Israel\nPlatform: LinkedIn\nExperience level: None\nSkills: \nJob description: Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.\nLink: https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466",
 'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'}

## Processing all questions

In [70]:
def generate_rag_answer(rec):
    question = rec["question"]
    doc_id = rec["document"]
    original_doc = doc_idx[doc_id]

    answer_llm = assistant.rag(question)
    answer_orig = assistant.build_context([original_doc])

    result = {
        "question": question,
        "answer_llm": answer_llm,
        "answer_orig": answer_orig,
        "document": doc_id,
    }

    return result

In [71]:
# Test it on one record:
answer_record = generate_rag_answer(ground_truth[0])
answer_record

{'question': 'support engineer jobs in Herzliya Israel with storage or backup systems',
 'answer_llm': 'Here are the most relevant jobs in Herzliya, Israel that match **support engineer** and **storage/backup systems**:\n\n### 1) Technical Support Engineer III, Israel — Cohesity\n- **City:** Herzliya, Tel Aviv District, Israel\n- **Why it matches:** This is the strongest match. It is a technical support role focused on **data protection**, **NetBackup Appliances**, **Cloud**, and related storage/backup areas.\n- **Relevant experience/skills:**  \n  - Enterprise technical support  \n  - Storage, networking, and virtualization environments  \n  - Data protection concepts  \n  - Remote file access protocols like **NFS** and **SMB**  \n  - Storage-related tools and platforms such as **VMware, Commvault, Symantec, DellEMC, NetApp**\n- **Link:** https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466\n\n### 2) Sales Data Analyst — SolarEdge Technologies\n- **City:** Herzliya, Tel Aviv District, Israel\n- **Why it might be relevant:** Not a support engineer role, but the company mentions **battery storage** and **backup systems** in its product line. If you were also open to data/analytics roles in a storage-related company, this could be relevant.\n- **Important note:** The actual job is a **data analyst** position, not support engineering.\n- **Link:** https://www.indeed.com/viewjob?jk=4e4c9d4656b02bc8\n\nIf you want, I can also narrow this down further to:\n- **only support engineer roles**\n- **only storage/backup-focused roles**\n- **only Herzliya jobs**',
 'answer_orig': "Title: Technical Support Engineer III, Israel\nCompany: Cohesity\nCity: Herzliya, Tel Aviv District, Israel\nPlatform: LinkedIn\nExperience level: None\nSkills: \nJob description: Cohesity is the leader in AI-powered data security. Over 13,600 enterprise customers, including over 85 of the Fortune 100 and nearly 70% of the Global 500, rely on Cohesity to strengthen their resilience while providing Gen AI insights into their vast amounts of data. Formed from the combination of Cohesity with Veritas’ enterprise data protection business, the company’s solutions secure and protect data on-premises, in the cloud, and at the edge. Backed by NVIDIA, IBM, HPE, Cisco, AWS, Google Cloud, and others, Cohesity is headquartered in Santa Clara, CA, with offices around the globe.We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design , and our culture.Want to join the leader in AI-powered data security?Join Cohesity as a Technical Support Engineer and become part of a team that is reshaping data management.This role will focus on supporting and resolving data protection issues in traditional platforms, DataProtect, NetBackup Appliances, Cloud, databases and more as you collaborate closely with highly skilled engineers from our team, striving to deliver flawless support and powerful solutions to our global customers.We are looking for a passionate Technical Support Engineer who possesses deep technical expertise, excellent troubleshooting experience, outstanding customer service and communications skills.HOW YOU'LL SPEND YOUR TIME HERE:Work with Cohesity customers to provide a timely resolution to technical issues.Use available tools to investigate and troubleshoot technical issuesRecord customer interactions, including investigation, troubleshooting, and the resolution of issuesWork closely with Cohesity engineering and account management teamsDemonstrate considerable judgment in selecting methods and techniques for obtaining solutionsProvide the best experience possible for Cohesity customersManage workload to ensure that all customer issues are resolved in a timely mannerAssist in the development of comprehensive and reusable self-service solutions for future incidentsDevelop knowledge base articles.Determine and communicate recommendations on Support readiness for new products and featuresProvide feedback to improve product\u202fquality/functionalityShifts may include standard business hours and/or early evenings, nights, to cover weekdays, weekends and holidays.WE'D LOVE TO TALK TO YOU IF YOU HAVE SOME OF THE FOLLOWING:Solid experience as an Enterprise Technical Support EngineerExperience working in a storage, networking and virtualization environmentStrong understanding of Operating SystemsAbility to analyse system diagnostics and clearly articulate the issue for the customerGood understanding of debugging utilities, with an emphasis on tcpdump, strace, wiresharkExperience with remote file access protocols, including NFS, SMB (CIFS)Solid experience with storage-related concepts, including virtualization and data protection (e.g. VMware, Commvault, Symantec, DellEMC, NetApp)Performance analysis experienceBachelor's Degree in Computer Science, Computer Networking or related with experience OR MS degree in Computer Science, Computer Networking or relatedDemonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision makingData Privacy Notice for Job Candidates:For information on personal data processing, please see our Privacy Policy.Equal Employment Opportunity Employer (EEOE)Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law.If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance.In-Office ExpectationsCohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing.Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location.\nLink: https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466",
 'document': 'https://il.linkedin.com/jobs/view/technical-support-engineer-iii-israel-at-cohesity-4415367466'}

In [72]:
# Import the parallel processing helper from the same utility file:
from concurrent.futures import ThreadPoolExecutor
from evaluation_utils import map_progress

In [73]:
# Run RAG for all ground truth questions
# Run RAG on many questions faster and in parallel, and show me the progress.

with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(pool, ground_truth, generate_rag_answer)

  0%|          | 0/25 [00:00<?, ?it/s]

In [74]:
answers = []

for answer_record in results:
    answers.append(answer_record)

In [75]:
df_answers = pd.DataFrame(answers)
df_answers.to_csv("data/rag_answers.csv", index=False)

# 5. LLM as a Judge

In the previous part, we generated RAG answers for our ground truth
questions. Now we need to decide whether these answers are good enough.

For offline evaluation, we have three things:

- the reference job description (built from the matched job's fields)
- the question generated from that job listing
- the answer generated by our RAG pipeline

## A->Q->A' evaluation

We'll compare the RAG answer with the reference description of the matched
job. This checks if the RAG pipeline is recommending the right job, with
the right details.

First, define the output format:

In [76]:
from pydantic import BaseModel, Field
from typing import Literal

class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description="Reasoning about the quality of the answer."
    )
    score: Literal["good", "bad"] = Field(
        description="'good' if the answer is correct and complete, 'bad' otherwise."
    )

In [77]:
# First, write the judge instructions.

aqa_judge_instructions = """
You are an expert evaluator. You will be given:
1. A search query from a job seeker
2. A reference description of the job that should match this query (ground truth)
3. An answer generated by an AI job-matching assistant

Your task is to decide if the AI answer correctly describes and recommends
the job in the reference description.

Rules:
- The AI answer does NOT need to be word-for-word identical
- It should mention the same key job details (role, company, location, skills, or experience level) where relevant
- Extra detail is fine as long as the core recommendation is correct
- Mark 'bad' only if the AI answer is wrong, recommends a different job, or misses the key point

Be fair and focus on correctness, not style.
""".strip()

In [78]:
# Then define the prompt template. This is the data we pass to the judge for each answer.

aqa_judge_prompt = """
Question:
{question}

Reference Job Description (ground truth):
{answer_orig}

AI Answer:
{answer_llm}
""".strip()

In [79]:
# Take one record
rec = answers[0]

In [80]:
# Create the judge prompt
prompt = aqa_judge_prompt.format(
    question=rec["question"],
    answer_orig=rec["answer_orig"],
    answer_llm=rec["answer_llm"]
)

In [81]:
# Call the judge
eval_result, usage = llm_structured_retry(
    openai_client,
    aqa_judge_instructions,
    prompt,
    AnswerEvaluation,
)

eval_result

AnswerEvaluation(reasoning='The answer correctly identifies the ground-truth job: Technical Support Engineer III at Cohesity in Herzliya, Israel, and accurately notes its focus on data protection, backup/storage-related environments, and relevant tools/skills. The extra mention of a SolarEdge Data Analyst role is irrelevant, but the primary recommendation is correct and matches the query.', score='good')

In [82]:
# Check the cost
calc_price(usage)

{'input_cost': 0.001089,
 'output_cost': 0.00038250000000000003,
 'total_cost': 0.0014715}

In [83]:
# Now put the same logic into a function
def evaluate_aqa(question, answer_orig, answer_llm, model="gpt-5.4-mini"):
    prompt = aqa_judge_prompt.format(
        question=question,
        answer_orig=answer_orig,
        answer_llm=answer_llm
    )

    result, usage = llm_structured_retry(
        openai_client,
        aqa_judge_instructions,
        prompt,
        AnswerEvaluation,
        model=model,
    )

    return result, usage

In [84]:
# Test it on the same record
eval_result, usage = evaluate_aqa(
    question=rec["question"],
    answer_orig=rec["answer_orig"],
    answer_llm=rec["answer_llm"]
)

eval_result

AnswerEvaluation(reasoning='The answer correctly identifies the ground-truth job: Technical Support Engineer III at Cohesity in Herzliya, and it accurately highlights the storage/data protection/backup system focus and relevant technologies. It also makes clear that Cohesity is the strongest match. Although it adds an irrelevant SolarEdge analyst role, that does not change the correctness of the main recommendation. ', score='good')

In [85]:
# Run the evaluation on all answers

def judge_record(rec):
    eval_result, usage = evaluate_aqa(
        question=rec["question"],
        answer_orig=rec["answer_orig"],
        answer_llm=rec["answer_llm"]
    )

    result = {
        "question": rec["question"],
        "document": rec["document"],
        "score": eval_result.score,
        "reasoning": eval_result.reasoning,
    }

    return result, usage

In [86]:
# Use the same parallel processing helper

from concurrent.futures import ThreadPoolExecutor

with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(pool, answers, judge_record)

  0%|          | 0/25 [00:00<?, ?it/s]

In [87]:
# Split the results

evaluations = []
usages = []

for evaluation, usage in results:
    evaluations.append(evaluation)
    usages.append(usage)

In [88]:
# Create a dataframe

df_eval = pd.DataFrame(evaluations)

In [89]:
# Calculate the total cost

calc_total_price(usages)

0.030969

In [90]:
good_count = (df_eval["score"] == "good").sum()
total_count = len(df_eval)
print(f"Good: {good_count}/{total_count} = {good_count/total_count:.2%}")

Good: 23/25 = 92.00%

In [91]:
# Look at the "bad" cases to understand what went wrong
df_eval[df_eval["score"] == "bad"].head()

,question,document,score,reasoning
17,research analyst job center district Israel Po...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,bad,The answer does identify a Junior Research Ana...
22,economics graduate analyst role in petah tikva,https://il.linkedin.com/jobs/view/junior-resea...,bad,The AI answer does not identify the reference ...

In [92]:
# Save the judged answers
df_eval.to_csv("data/rag_evaluations.csv", index=False)

In [93]:
df_eval

,question,document,score,reasoning
0,support engineer jobs in Herzliya Israel with ...,https://il.linkedin.com/jobs/view/technical-su...,good,The answer correctly identifies the ground-tru...
1,technical support role in Tel Aviv area workin...,https://il.linkedin.com/jobs/view/technical-su...,good,The answer correctly identifies the Cohesity T...
2,enterprise support engineer opening Israel tro...,https://il.linkedin.com/jobs/view/technical-su...,good,The answer correctly identifies the ground-tru...
3,job for data protection / backup support engin...,https://il.linkedin.com/jobs/view/technical-su...,good,The AI answer correctly identifies the Cohesit...
4,customer-facing tech support position in Israe...,https://il.linkedin.com/jobs/view/technical-su...,good,The AI answer correctly identifies the referen...
5,entry level data analyst job tel aviv excel po...,https://www.indeed.com/viewjob?jk=466348bfe369...,good,The AI answer correctly identifies the referen...
6,junior research analyst job in tel aviv no exp...,https://www.indeed.com/viewjob?jk=466348bfe369...,good,The AI answer correctly identifies the ground-...
7,market research analyst role israel consumer g...,https://www.indeed.com/viewjob?jk=466348bfe369...,good,The AI answer correctly identifies the ground-...
8,graduate analytics position tel aviv retail data,https://www.indeed.com/viewjob?jk=466348bfe369...,good,The AI answer correctly identifies the referen...
9,data analysis job for economics graduate in te...,https://www.indeed.com/viewjob?jk=466348bfe369...,good,The AI answer correctly identifies the ground-...
10,junior data analyst jobs in raanana,https://www.indeed.com/viewjob?jk=241e7d5657b0...,good,The AI answer correctly matches the reference ...
11,entry level market research analyst israel no ...,https://www.indeed.com/viewjob?jk=241e7d5657b0...,good,The answer correctly identifies the reference ...
12,excel powerpoint analyst role near tel aviv area,https://www.indeed.com/viewjob?jk=241e7d5657b0...,good,The AI answer correctly identifies the ground-...
13,business analyst trainee FMCG company raanana,https://www.indeed.com/viewjob?jk=241e7d5657b0...,good,The AI answer correctly identifies StoreNext’s...
14,data research job for recent graduates in israel,https://www.indeed.com/viewjob?jk=241e7d5657b0...,good,The AI answer correctly identifies the ground-...
15,entry level data analyst jobs in Israel econom...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,good,The AI answer correctly identifies the ground-...
16,junior market research analyst FMCG Israel no ...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,good,The AI answer correctly identifies the ground-...
17,research analyst job center district Israel Po...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,bad,The answer does identify a Junior Research Ana...
18,business analyst for consumer goods company in...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,good,The AI answer correctly identifies the ground-...
19,analyst role near Jerusalem area with Excel an...,https://www.indeed.com/viewjob?jk=c54a7af776fd...,good,The AI answer identifies the correct ground-tr...
20,junior data analyst jobs petah tikva excel,https://il.linkedin.com/jobs/view/junior-resea...,good,The reference job is a Junior Research Analyst...
21,entry level market research analyst israel no ...,https://il.linkedin.com/jobs/view/junior-resea...,good,The answer correctly identifies the reference ...
22,economics graduate analyst role in petah tikva,https://il.linkedin.com/jobs/view/junior-resea...,bad,The AI answer does not identify the reference ...
23,consumer goods data analysis jobs center district,https://il.linkedin.com/jobs/view/junior-resea...,good,The AI answer correctly identifies the referen...
24,excel powerpoint research analyst full time is...,https://il.linkedin.com/jobs/view/junior-resea...,good,The answer correctly identifies the ground-tru...

In [94]:
good_count = (df_eval["score"] == "good").sum()
total_count = len(df_eval)
print(f"Good: {good_count}/{total_count} = {good_count/total_count:.2%}")

Good: 23/25 = 92.00%

LLM-judge eval — tuned boost weights (skills:4.0, Title:3.0, Job_Description:3.0) → 23/25 good answers, up from 19/25 ("Title": 3.0, "skills": 0.5)

So, thanks to this evaluation we now know how to properly use the search and how important is the hibris search. Using the keybord search was not enougth!

## Evaluation conclusion


The LLM-as-a-judge evaluation showed a clear improvement after tuning the keyword search boost weights and using hybrid search.

The best keyword boost configuration was:

```python
boost_dict = {
    "skills": 4.0,
    "Title": 3.0,
    "Job_Description": 3.0
}